databases:
  - name: registration-test
    databaseName: registration-test
    user: registration-test

services:
  - type: web
    name: registration-test
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: registration-test
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false